### ISSUE TITLE
node 0.12.0, node-inspector 0.9.1: does not work with --debug-brk

### ISSUE THREAD

**Issue by briandela** [node-inspector/node-inspector#570] opened 2015-02-26 22:55 UTC
If I start a script using `node --debug-brk` I see that it is paused with the message `debugger listening on port 5858`. As soon as I load the node-inspector page at `http://127.0.0.1:8080/debug?port=5858` the script continues immediately.

This makes it impossible to debug script startup, tests, etc.

When I switch back to node 0.10.33, loading the node-inspector page does not cause the script to continue and I can debug correctly.

Any ideas on how to get node-inspector working with node 0.12.0?

Version details:
node: 0.12.0
v8: 3.28.73
node-inspector: 0.9.1

OS: OSX Yosemite (10.10.2)

**Comment by tmacie** [comment] 2015-02-26 22:55
+1

**Comment by briandela** [comment] 2015-02-26 23:02
This may be similar to #534

**Comment by arielschiavoni** [comment] 2015-03-03 08:50
@briandela I had the exact same problem. I can't debug with node v0.12 and node-inspector v0.9.1.
However node v0.10.x and node-inspector v0.9.1 works well.

+1

**Comment by bajtos** [comment] 2015-03-04 09:03
Closing as a duplicate of #534.

**Closed by bajtos** 2015-03-04 09:03 UTC

**Comment by castasamu** [comment] 2015-03-06 23:24
+1
