### ISSUE TITLE
i can׳t run it on ubuntu 

### ISSUE THREAD

**Issue by roysG** [node-inspector/node-inspector#567] opened 2015-02-23 22:29 UTC
debugger listening on port 5858
Node Inspector is now available from http://127.0.0.1:8080/debug?port=5858
Debugging `server/app.js`

Failed to open socket on port 5858, waiting 1000 ms before retrying

/usr/lib/node_modules/node-inspector/node_modules/biased-opener/index.js:97
        var goodEnough = isDefaultBrowserGoodEnough(browserInfo.commonName, pr
                                                               ^
TypeError: Cannot read property 'commonName' of undefined
    at /usr/lib/node_modules/node-inspector/node_modules/biased-opener/index.js:97:64
    at /usr/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/x-default-browser/lib/detect-linux.js:9:13
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

**Comment by 3y3** [comment] 2015-02-23 23:27
This is bug in `biased-opener`
/cc @jakub-g

**Comment by jakub-g** [comment] 2015-02-24 07:03
I will investigate ASAP.

@roysG can you tell the following:

1. Version of ubuntu

2. Version of node

3. What is your default web browser of the os?

**Comment by roysG** [comment] 2015-02-24 12:10
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

node version: v0.10.36

i am using mac as my private computer and i am using chrome



node.js:838
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Function.startup.resolveArgv0 (node.js:838:23)
    at startup (node.js:58:13)
    at node.js:929:3

**Comment by jakub-g** [comment] 2015-02-25 08:26
Well the issue in biased-opener is  silly one, simply that I can't check for an error and assume there would be no error.

@roysG I opened a follow-up issue on my own repo to not clutter here too much
https://github.com/jakub-g/x-default-browser/issues/1
can you please have a look to help me understand the issue better?

**Comment by bajtos** [comment] 2015-03-04 09:14
Closing as a duplicate of https://github.com/jakub-g/x-default-browser/issues/1. Thank you @jakub-g for taking care of this.

**Closed by bajtos** 2015-03-04 09:14 UTC
Labels: BUG, Third party
