### ISSUE TITLE
Optionally disable some injections in app

### ISSUE THREAD

**Issue by maximilianschmitt** [node-inspector/node-inspector#650] opened 2015-05-20 19:36 UTC
Hi, maybe I don't understand completely what is going on but I've noticed that strings are being retained when they are passed to `console.log`.

I'm running `io.js v2.0.1`.

```
setInterval(sayHello, 5);

function sayHello() {
  console.log('hello');
}
```

This script produces the following heap timeline:

![screen shot 2015-05-20 at 21 30 31](https://cloud.githubusercontent.com/assets/3694962/7734629/b6ef48f8-ff37-11e4-8930-8d3d10aa10a9.png)

As you can see, all the strings are being retained.

I wonder if this is expected behaviour or if it's a bug with node.js or node-inspector. If you change `console.log` to `process.stdout.write`, it doesn't leak:

```
setInterval(sayHello, 5);

function sayHello() {
  process.stdout.writeline('hello');
}
```

Here is the heap timeline:

![screen shot 2015-05-20 at 21 35 27](https://cloud.githubusercontent.com/assets/3694962/7734699/2d327756-ff38-11e4-9ebe-eaf5823b012f.png)

**Comment by 3y3** [comment] 2015-05-20 19:53
This is expected behavior:
We wrap all console functions, this allow us to translate all console output to web interface.
We don't wrap stdout itself, because it is out of scope of DevTools API.
So when you use console.log(object), we need to store this object in memory as long as it is possible.
To delete it from memory use `clear` button in console tab.

**Comment by 3y3** [comment] 2015-05-20 19:58
In other words this is expected controllable memory leak.
There are some discutable points:
1. It maybe reasonable to allow users to disable console wrapping, for clear memory testing. (Allow users to disable any injectable feature by name)
2. This is hard in realisation but may be reasonable to hide all mirror objects in heap snapshot. I need to inspect how this realised in webkit.

**Comment by maximilianschmitt** [comment] 2015-05-28 02:02
Hey! Thanks for the fast response! :)

It's good to know that this is expected behaviour. I wish I could add something to the discussion but I'm afraid I don't know too much about debugging tools and V8 internals. Although having the ability to somehow disable the console-related leaks would be something I would use as I primarily use node-inspector for memory profiling.

**Comment by 3y3** [comment] 2016-02-07 17:31
Released some versions ago.
Usage `--no-inject.console`, `--no-inject.network`, `--no-inject.profiles`

**Closed by 3y3** 2016-02-07 17:31 UTC
Labels: Enhancement
