### ISSUE TITLE
Possible issue with debugging gulp with node v0.12 and node-inspector

### ISSUE THREAD

**Issue by jasnell** [node-inspector/node-inspector#577] opened 2015-03-04 03:50 UTC
Please see joyent/node#9322

There's a possible issue with using node-inspector and node v0.12 to debug gulp. It's not yet clear where exactly the issue is and I wanted to check here before digging in too far.

**Comment by bajtos** [comment] 2015-03-04 09:04
Closing as a duplicate of #534.

**Closed by bajtos** 2015-03-04 09:04 UTC
