### ISSUE TITLE
Hangs during CPU profiling

### ISSUE THREAD

**Issue by dillonkrug** [node-inspector/node-inspector#574] opened 2015-02-28 20:56 UTC
Apparent with node versions 0.12.0, 0.11.16, and 0.10.29

I also tried various versions of node-inspector back to v0.8.3

Steps to reproduce:
 - start node-inspector
 - start node --debug app (my web app)
 - open node inspector in the browser
 - start CPU profiler
 - hit a couple endpoints on my api

After a few (<10) requests, my app hangs with the cpu at 100%

Don't know if it's helpful, but I sampled the process in activity monitor, which you can see in [this gist](https://gist.github.com/dillonkrug/ca7dad3482d48e146adc)

(edit: I should point out that I sampled many times, repeating the whole process, and it always looked the same - __psynch_mutexwait seems to have something to do with... something)

I did some very unscientific testing, and it appears that this problem happens even when the only thing the app is doing is serving a static file.

**Comment by bajtos** [comment] 2015-03-04 09:17
Can anybody else reproduce this problem?

**Comment by rcrichton** [comment] 2015-03-12 11:29
I have seen the same behaviour with node 0.12. I put it down to a v8-profiler not supporting the latest version of v8 used in node 0.12.

**Comment by 3y3** [comment] 2015-04-24 18:01
Fixed in `0.10.0` release. Reopen this bug if the problem still persists for you.

**Comment by allthetime** [comment] 2015-04-24 19:47
I'm on node `v0.12.2` using node-inspector `v0.10.0` and I can start profiling, but after stopping it continues to say "recording..." underneath the profile icon and node-inspector freezes.

**Comment by 3y3** [comment] 2015-04-27 09:32
@allthetime  , can you completely reinstall node-inspector
```bash
npn uninstall -g node-inspector
npm install -g node-inspector
```
Say me if it will help you.

**Comment by carlhopf** [comment] 2015-06-05 13:10
Same issue here, using node 0.12.4, node-inspector 0.10.1 (tried to reinstall aswell) and v8-profiler 5.2.9.

Most of the time, profiling will hang on "recording..." after stopping manually using the inspector.

Profiles started/stopped via profiler.startProfiling('name') will not appear in the inspector at all.

**Comment by kimmobrunfeldt** [comment] 2015-06-08 08:13
I also hit this problem ~every time when doing more than 5-10 concurrent requests to my express app. node 0.12.2, node-inspector 0.10.1

**Comment by elmasse** [comment] 2015-06-12 17:06
Not sure if it's the same issue but, when start profiling code that's stopped in a breakpoint, source tab is disabled and there is no way to run the code.

node-inspector v0.10.1
node v0.12.4
chrome v43

See attached image:
![screen shot 2015-06-12 at 2 02 03 pm](https://cloud.githubusercontent.com/assets/223235/8135242/1be268ae-110c-11e5-994b-333a0e9b4d8a.png)

**Comment by frontierpsycho** [comment] 2015-06-16 08:59
I think I hit the same snag on 0.10.2.

**Comment by eabovsky** [comment] 2015-06-16 21:14
Same here. Used to work file on .10. When I went to .12 the CPU profiler just freezes my process.

**Comment by KylePDavis** [comment] 2015-06-17 18:10
Getting the same as @elmasse.

Reproduced with `node-debug gulp` using:
- Mac OS X v10.10.3 (Yosemite)
- Chrome 42.0.2311.90 (64-bit)
- `node-inspector` - v0.10.2
- `node` - v0.12.2, v0.12.4

If it helps, I noticed that if you refresh the page you can continue debugging and the "Profiles" page goes back to it's original state.

**Comment by docksteaderluke** [comment] 2015-06-17 19:03
+ 1. Same setup as @KylePDavis

**Comment by tysonstewart** [comment] 2015-06-26 19:48
Also +1, same setup as @KylePDavis.

**Comment by 3y3** [comment] 2015-06-26 19:57
@tysonstewart , can you please submit issue on node 0.12.5?

**Comment by JeffML** [comment] 2015-07-03 00:19
on a Mac (Yosemite, node 0.12.2, newly installed node-inspector) I see:
Error: Cannot find module '/opt/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v14-darwin-x64/debug.node'

**Comment by tysonstewart** [comment] 2015-07-03 01:35
@3y3 Apologies; missed your reply. Confirmed, it still happens on 0.12.5.

**Comment by sebastian-nowak** [comment] 2015-07-05 09:50
I have the same problem under node 0.12.5, node-inspector 0.10.2.

**Comment by 3y3** [comment] 2015-07-05 13:46
Maybe anyone can provide small example of code?

**Comment by dillonkrug** [comment] 2015-07-22 18:52
I'm guessing this may be related: https://github.com/joyent/node/issues/14576

Upgrading Node from v0.12.0 to v0.12.7 appears to have fixed the problem completely

**Comment by 3y3** [comment] 2015-07-22 22:52
@dillonkrug , thank you for information!
Waiting feedback from issue starter or other subscribers.

**Comment by elmasse** [comment] 2015-07-22 23:24
Tested with: 
node v0.12.7 
node-inspector v0.11.1
OSX 10.10.4

Issue still there for me. 
Steps:
- `node-debug index.js` (with debugger statement line 1) - or `node-debug --debug-brk index.js`
- go to profiles
- Select 'Collect JavaScript CPU Profile'
- press start

Source tab is disabled (as all other tabs except Profile). No way to keep running the program without stoping the profile.

My 2 cents.
Max

**Comment by dillonkrug** [comment] 2015-07-23 00:13
I used the profiler pretty heavily today and, after upgrading node, everything seemed fine.

The source tab being disabled during profiling is unrelated to the original issue, so I would be fine closing this particular ticket, and then others who are concerned about that can open a new one for that problem.

**Comment by mbroadst** [comment] 2015-09-04 22:12
@elmasse have you found a way to collect a cpu profile? I'm running into the same issues as you, I assumed collecting the profile would start the script but I just get profiling data related to node-inspector, nothing about my script

**Comment by elmasse** [comment] 2015-09-04 23:28
@mbroadst I have been using the v8-profiler and save it to a file manually, then load it on chrome. Still, it doesn't work well all the time. 

This seems to be related to Chrome Dev Tools. I tried iron-node and experiencing the exact same issue.

**Comment by felipou** [comment] 2015-09-11 15:48
On Mac OS X I was having this problem on node v0.12.4. Just updated to v0.12.7 and it fixed the problem. Using node-inspector 0.12.3 in both cases.

**Closed** 2015-12-06 21:06 UTC
Labels: BUG, Triaging

**Comment by gebrits** [comment] 2016-01-18 20:02
Seeing this issue on node 5.1.0. 
No problems on 0.12.7

**Comment by robertjd** [comment] 2016-05-09 18:32
I also had the hanging problem, with Node 0.12.2.  Switching to 4.2.3 has solved the problem for me.
