### ISSUE TITLE
Running with io.js

### ISSUE THREAD

**Issue by blendsdk** [node-inspector/node-inspector#546] opened 2015-02-02 09:59 UTC
Hi, 

I was wondering if node-inspector would also work with io.js?

Regards,
Gevik.

**Comment by cowabunga1** [comment] 2015-02-03 06:02
Hello, yes it is very necessary!

**Comment by blendsdk** [comment] 2015-02-03 06:08
I tried to install install it but it breaks on OSX!

**Comment by Pana** [comment] 2015-02-05 02:10
+1 breaks on OSX , does your guys have plan to support iojs

**Comment by ide** [comment] 2015-02-07 00:39
The build error is in v8-debug. See https://github.com/node-inspector/v8-debug/issues/10.

**Comment by krnlde** [comment] 2015-02-11 20:53
:+1: would love to have that for io.js

**Comment by tomzx** [comment] 2015-02-15 14:08
@ide What about the very old (0.4.32 vs 0.7.1) version of `websocket` (ws)? The build errors I'm getting are related to it when I try to install `node-inspector`. I guess it's only the first error in the chain of things that needs to be fixed (and you manually changed that dependency in your package.json)?

**Comment by mrgamer** [comment] 2015-02-15 15:52
just reporting that with v8-debug `0.4.0` (just released) I can compile `node-inspector` correctly on linux

Still awaiting for a release because compiling on windows is a PITA :astonished:

**Comment by tomzx** [comment] 2015-02-15 16:07
Works with `v8-debug` @ `v0.4.0` for me too on Windows :+1:

**Comment by 3y3** [comment] 2015-02-15 16:45
@mrgamer , @tomzx , hey wait sometime =) I prepare the release pr.

**Comment by mahnunchik** [comment] 2015-02-17 18:29
+1

**Comment by jimthedev** [comment] 2015-02-25 02:29
So, the current version of node-inspector now installs with iojs and runs but some features don't work if I am seeing this properly. I'm using nvm to switch between node and iojs and am blowing away my node_modules in between to force a rebuild. 

There are still about 20 tests that seem to be failing when using iojs. 

Specifically it seems like the number 14 and 15 are confusing to me.

I am running the following commands to get my test results:

```bash
git clone https://github.com/node-inspector/node-inspector.git
cd node-inspector
nvm install iojs
npm install
./node_modules/mocha/bin/mocha --timeout 5000
```

And here are the results:

```bash
child_process: customFds option is deprecated, use stdio instead.


  CallFramesProvider
    1) gets stack trace
    ✓ retrieves specified number of stack traces when configured (481ms)

  ConsoleAgent
    ✓ should translate console message to frontend
    ✓ should update repeat counter on repeated message
    ✓ should translate objects
    ✓ should translate async console message to frontend
    ✓ should clear messages

  ConsoleClient
    ✓ should match only valid consoleId
    2) should provide object data
    3) should provide object (with internal properties) data
    4) should return error on not existed object
    5) should return error on not existed message

  DebuggerAgent
    sets variable value
      ✓ to a string
      ✓ to a number
      ✓ to null
      ✓ to undefined
      ✓ to an object
      ✓ to a function
    nodeVersionHasSetVariableValue
      ✓ returns false for v0.8.20
      ✓ returns false for v0.10.11
      ✓ returns true for v0.10.12
      ✓ returns false for v0.11.1
      ✓ returns true for v0.11.2
      ✓ returns true for v0.12.0
      ✓ returns true for v1.0.0
    evaluateOnCallFrame
      ✓ truncates String values at 10,000 characters
    resume()
      ✓ does not throw an error
    setBreakpointByUrl()
      ✓ does not throw an error

  DebuggerClient
    evaluteGlobal
      ✓ returns full value of a long string
    isRunning
      ✓ is updated on connect in --debug-brk mode
      ✓ is updated on break
    request
      ✓ sends correct data length (406ms)

  FrontendCommandHandler
    ✓ defers "scriptParsed" events until "Page.getResourceTree" (989ms)

  HeapProfiler Agent
    6) should take snapshot with report progress
    7) should get snapshot
    8) should return error if requested snapshot not found
    9) should receive snapshots list
    10) should remove snapshot
    11) should return error if removing snapshot not found
    12) should start tracking
    13) should stop tracking

  HeapProfilerClient
    ✓ should match only valid heapObjectId

  InjectorClient
    with inject=false
      ✓ ignores break events not created by the injector
      ✓ checks that application paused by injector
      ✓ breaks the injection flow with injected=false
    with inject=true
      ✓ is ready to inject
      ✓ inject server (66ms)
      ✓ does not need to inject if already injected
      ✓ notify that is already injected
      ✓ would close on "close" debuggerClient
      ✓ is ready to inject after close
    with inject=true and debug-brk flag
      ✓ connects to server (102ms)
    works with events.
      14) Register event handle in app and emits it
    works with commands.
      15) Registers command in app and responds to it

  NetworkAgent
    loadResourceForFrontend
      ✓ should load data URLs

  PageAgent
    getResourceContent()
      ✓ does not throw an error

  Profiler Agent
    16) should start profiling
    17) should stop profiling
    18) should get profile header
    19) should get profiles list
    20) should clear profiles
    nodeVersionIsCompatible
      ✓ returns false for v0.10.29
      ✓ returns false for v0.11.12
      ✓ returns true for v0.11.13
      ✓ returns true for v0.12.0
      ✓ returns true for v1.0.0

  RuntimeAgent
    ✓ gets scope properties (400ms)
    ✓ filter null __proto__ (528ms)
    ✓ returns object properties with metadata (441ms)
    ✓ returns empty result for accessorPropertiesOnly:true (453ms)
    ✓ returns __proto__ for ownProperties:true (482ms)
    ✓ calls function on an object to get completions (473ms)
    calls function on an object to change property value
      ✓ to a string
      ✓ to a number
      ✓ to null
      ✓ to undefined
      ✓ to an object
      ✓ to a function

  ScriptFileStorage
    ✓ saves new content without node.js module wrapper (405ms)
    ✓ preserves shebang when saving new content (410ms)
    ✓ loads content with node.js module wrapper
    ✓ loads content without shebang
    ✓ finds application root for subdir/app.js by checking package.json file in parent
    ✓ finds application root for root/app.js with no package.json files around
    ✓ finds application root for root/app.js by checking package.json file in root/
    ✓ finds also files in start directory
    ✓ lists only well-known subdirectories when package.json is missing
    ✓ lists all subdirectories when package.json is present
    ✓ removes duplicate entries from files found
    ✓ excludes files to hide
    ✓ disables preloading files

  ScriptManager
    findSourceByID()
      ✓ returns stored source
      ✓ returns undefined for unknown id
    reset()
      ✓ removes all stored scripts
    normalizeName()
      ✓ returns unchanged name for main script on Linux
      ✓ returns unchanged name for not main scripts

  Config
    from argv
      ✓ handles --help
      ✓ handles --version
      ✓ handles --web-port
      ✓ handles --web-host
      ✓ handles --debug-port
      ✓ handles --save-live-edit
      ✓ handles --preload
      ✓ handles --hidden
      ✓ handles --stack-trace-limit
      ✓ handles --ssl-key defined
      ✓ handles --ssl-cert defined
      ✓ handles --ssl-key not defined
      ✓ handles --ssl-cert not defined
      ✓ handles --nodejs
      ✓ handles --debug-brk
      ✓ handles --cli
    defaults
      ✓ have expected values
      ✓ have expected values in node-debug mode
    serializeOptions
      ✓ without filtering
      ✓ with filtering
    filterNodeDebugOptions
      ✓ works correctly
    filterDefaultValues
      ✓ works correctly

  convert
    ✓ Check "Invalid Date" object
    v8NameToInspectorUrl
      ✓ preserves node.js internal modules as filename without path
      ✓ converts unix path to file:// URL
      ✓ converts windows disk path to file:// URL
      ✓ converts windows UNC path to file:// URL
      ✓ converts undefined path to empty string
    inspectorUrlToV8Name
      ✓ returns filename without path for node.js internal modules
      ✓ converts URL to unix path
      ✓ converts URL to windows disk path
      ✓ converts URL to windows UNC
    v8RefToInspectorObject
      ✓ returns type, objectId and className for objects
      ✓ returns type, objectId for functions
      ✓ describes string value
      ✓ describes object type
      ✓ appends length to Array description
      ✓ appends length to Buffer description
      ✓ appends formatted date to Date description by calling toString on the date
    v8ResultToInspectorResult
      ✓ convert regexp as object
      ✓ converts error as object

  index
    build_url
      ✓ should build an http URL
      ✓ should build an http URL

  node-debug
    argument parser
      ✓ handles `app.js`
      ✓ handles empty arguments
      ✓ handles options
      ✓ handles long options with =val and no script file
      ✓ handles nodejs options
      ✓ ignores options of the debugged application
      ✓ supports slc-debug argument names
      ✓ supports node-inspector argument names
      ✓ forwards unknown options to node-inspector


  128 passing (19s)
  20 failing

  1) CallFramesProvider gets stack trace:

      frame[0].location
      + expected - actual

      +"{\"scriptId\":\"36\",\"lineNumber\":8,\"columnNumber\":4}"
      -"{\"scriptId\":\"44\",\"lineNumber\":8,\"columnNumber\":4}"

      at assertJSONEqual (/Users/jimthedev/projects/node-inspector/test/CallFramesProvider.js:101:36)
      at assertFrame (/Users/jimthedev/projects/node-inspector/test/CallFramesProvider.js:85:3)
      at /Users/jimthedev/projects/node-inspector/test/CallFramesProvider.js:31:9
      at /Users/jimthedev/projects/node-inspector/node_modules/async/lib/async.js:254:17
      at done (/Users/jimthedev/projects/node-inspector/node_modules/async/lib/async.js:135:19)
      at /Users/jimthedev/projects/node-inspector/node_modules/async/lib/async.js:32:16
      at /Users/jimthedev/projects/node-inspector/node_modules/async/lib/async.js:251:21
      at Object.CallFramesProvider._convertDebuggerFrameToInspectorFrame (/Users/jimthedev/projects/node-inspector/lib/CallFramesProvider.js:57:5)
      at /Users/jimthedev/projects/node-inspector/node_modules/async/lib/async.js:249:17
      at /Users/jimthedev/projects/node-inspector/node_modules/async/lib/async.js:125:13
      at Array.forEach (native)
      at _each (/Users/jimthedev/projects/node-inspector/node_modules/async/lib/async.js:46:24)
      at async.each (/Users/jimthedev/projects/node-inspector/node_modules/async/lib/async.js:124:9)
      at _asyncMap (/Users/jimthedev/projects/node-inspector/node_modules/async/lib/async.js:248:13)
      at Object.map (/Users/jimthedev/projects/node-inspector/node_modules/async/lib/async.js:219:23)
      at Object.CallFramesProvider._convertBacktraceToCallFrames (/Users/jimthedev/projects/node-inspector/lib/CallFramesProvider.js:38:11)
      at Object.<anonymous> (/Users/jimthedev/projects/node-inspector/lib/CallFramesProvider.js:31:14)
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:122:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  2) ConsoleClient should provide object data:

      Uncaught AssertionError: expected { Object (handle, type, ...) } to deeply equal { Object (handle, type, ...) }
      + expected - actual

         "handle": 7
         "properties": [
           {
             "name": "a"
      +      "propertyType": 1
      -      "propertyType": 0
             "ref": 11
           }
         ]
         "protoObject": {

      at Assertion.assertEqual (/Users/jimthedev/projects/node-inspector/node_modules/chai/lib/chai/core/assertions.js:427:19)
      at Assertion.ctx.(anonymous function) [as equal] (/Users/jimthedev/projects/node-inspector/node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at /Users/jimthedev/projects/node-inspector/test/ConsoleAgent.js:111:36
      at ConsoleClient.<anonymous> (/Users/jimthedev/projects/node-inspector/lib/ConsoleClient.js:28:7)
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:122:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  3) ConsoleClient should provide object (with internal properties) data:

      Uncaught AssertionError: expected { Object (handle, type, ...) } to deeply equal { Object (handle, type, ...) }
      + expected - actual

         "handle": 7
         "properties": [
           {
             "name": "a"
      +      "propertyType": 1
      -      "propertyType": 0
             "ref": 11
           }
         ]
         "protoObject": {

      at Assertion.assertEqual (/Users/jimthedev/projects/node-inspector/node_modules/chai/lib/chai/core/assertions.js:427:19)
      at Assertion.ctx.(anonymous function) [as equal] (/Users/jimthedev/projects/node-inspector/node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at /Users/jimthedev/projects/node-inspector/test/ConsoleAgent.js:111:36
      at ConsoleClient.<anonymous> (/Users/jimthedev/projects/node-inspector/lib/ConsoleClient.js:28:7)
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:122:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  4) ConsoleClient should return error on not existed object:

      Uncaught AssertionError: expected { Object (handle, type, ...) } to deeply equal { Object (handle, type, ...) }
      + expected - actual

         "handle": 7
         "properties": [
           {
             "name": "a"
      +      "propertyType": 1
      -      "propertyType": 0
             "ref": 11
           }
         ]
         "protoObject": {

      at Assertion.assertEqual (/Users/jimthedev/projects/node-inspector/node_modules/chai/lib/chai/core/assertions.js:427:19)
      at Assertion.ctx.(anonymous function) [as equal] (/Users/jimthedev/projects/node-inspector/node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at /Users/jimthedev/projects/node-inspector/test/ConsoleAgent.js:111:36
      at ConsoleClient.<anonymous> (/Users/jimthedev/projects/node-inspector/lib/ConsoleClient.js:28:7)
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:122:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  5) ConsoleClient should return error on not existed message:

      Uncaught AssertionError: expected { Object (handle, type, ...) } to deeply equal { Object (handle, type, ...) }
      + expected - actual

         "handle": 7
         "properties": [
           {
             "name": "a"
      +      "propertyType": 1
      -      "propertyType": 0
             "ref": 11
           }
         ]
         "protoObject": {

      at Assertion.assertEqual (/Users/jimthedev/projects/node-inspector/node_modules/chai/lib/chai/core/assertions.js:427:19)
      at Assertion.ctx.(anonymous function) [as equal] (/Users/jimthedev/projects/node-inspector/node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at /Users/jimthedev/projects/node-inspector/test/ConsoleAgent.js:111:36
      at ConsoleClient.<anonymous> (/Users/jimthedev/projects/node-inspector/lib/ConsoleClient.js:28:7)
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:122:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  6) HeapProfiler Agent should take snapshot with report progress:
     Uncaught AssertionError: expected 'Error: Unknown command "HeapProfiler.takeHeapSnapshot" in request' to equal null
      at /Users/jimthedev/projects/node-inspector/test/HeapProfilerAgent.js:67:26
      at HeapProfilerAgent.<anonymous> (/Users/jimthedev/projects/node-inspector/lib/HeapProfilerAgent.js:83:9)
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:117:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  7) HeapProfiler Agent should get snapshot:
     Uncaught AssertionError: expected 'Error: Unknown command "HeapProfiler.takeHeapSnapshot" in request' to equal null
      at /Users/jimthedev/projects/node-inspector/test/HeapProfilerAgent.js:67:26
      at HeapProfilerAgent.<anonymous> (/Users/jimthedev/projects/node-inspector/lib/HeapProfilerAgent.js:83:9)
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:117:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  8) HeapProfiler Agent should return error if requested snapshot not found:
     Uncaught AssertionError: expected 'Error: Unknown command "HeapProfiler.takeHeapSnapshot" in request' to equal null
      at /Users/jimthedev/projects/node-inspector/test/HeapProfilerAgent.js:67:26
      at HeapProfilerAgent.<anonymous> (/Users/jimthedev/projects/node-inspector/lib/HeapProfilerAgent.js:83:9)
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:117:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  9) HeapProfiler Agent should receive snapshots list:
     Uncaught AssertionError: expected 'Error: Unknown command "HeapProfiler.takeHeapSnapshot" in request' to equal null
      at /Users/jimthedev/projects/node-inspector/test/HeapProfilerAgent.js:67:26
      at HeapProfilerAgent.<anonymous> (/Users/jimthedev/projects/node-inspector/lib/HeapProfilerAgent.js:83:9)
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:117:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  10) HeapProfiler Agent should remove snapshot:
     Uncaught AssertionError: expected 'Error: Unknown command "HeapProfiler.takeHeapSnapshot" in request' to equal null
      at /Users/jimthedev/projects/node-inspector/test/HeapProfilerAgent.js:67:26
      at HeapProfilerAgent.<anonymous> (/Users/jimthedev/projects/node-inspector/lib/HeapProfilerAgent.js:83:9)
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:117:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  11) HeapProfiler Agent should return error if removing snapshot not found:
     Uncaught AssertionError: expected 'Error: Unknown command "HeapProfiler.takeHeapSnapshot" in request' to equal null
      at /Users/jimthedev/projects/node-inspector/test/HeapProfilerAgent.js:67:26
      at HeapProfilerAgent.<anonymous> (/Users/jimthedev/projects/node-inspector/lib/HeapProfilerAgent.js:83:9)
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:117:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  12) HeapProfiler Agent should start tracking:
     Uncaught AssertionError: expected 'Error: Unknown command "HeapProfiler.takeHeapSnapshot" in request' to equal null
      at /Users/jimthedev/projects/node-inspector/test/HeapProfilerAgent.js:67:26
      at HeapProfilerAgent.<anonymous> (/Users/jimthedev/projects/node-inspector/lib/HeapProfilerAgent.js:83:9)
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:117:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  13) HeapProfiler Agent should stop tracking:
     Uncaught AssertionError: expected 'Error: Unknown command "HeapProfiler.takeHeapSnapshot" in request' to equal null
      at /Users/jimthedev/projects/node-inspector/test/HeapProfilerAgent.js:67:26
      at HeapProfilerAgent.<anonymous> (/Users/jimthedev/projects/node-inspector/lib/HeapProfilerAgent.js:83:9)
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:117:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  14) InjectorClient works with events. Register event handle in app and emits it:
     Error: timeout of 5000ms exceeded
      at null.<anonymous> (/Users/jimthedev/projects/node-inspector/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:90:15)

  15) InjectorClient works with commands. Registers command in app and responds to it:
     Uncaught AssertionError: expected 'Error: Unknown command "testcommand" in request' to equal null
      at /Users/jimthedev/projects/node-inspector/test/InjectorClient.js:229:32
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:117:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  16) Profiler Agent should start profiling:
     Error: done() invoked with non-Error: Error: Unknown command "Profiler.start" in request
      at /Users/jimthedev/projects/node-inspector/node_modules/mocha/lib/runnable.js:223:25
      at /Users/jimthedev/projects/node-inspector/test/ProfilerAgent.js:19:25
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:117:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  17) Profiler Agent should stop profiling:
     Error: done() invoked with non-Error: Error: Unknown command "Profiler.stop" in request
      at /Users/jimthedev/projects/node-inspector/node_modules/mocha/lib/runnable.js:223:25
      at /Users/jimthedev/projects/node-inspector/test/ProfilerAgent.js:33:25
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:117:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  18) Profiler Agent should get profile header:
     Error: done() invoked with non-Error: Error: Unknown command "Profiler.getCPUProfile" in request
      at /Users/jimthedev/projects/node-inspector/node_modules/mocha/lib/runnable.js:223:25
      at /Users/jimthedev/projects/node-inspector/test/ProfilerAgent.js:64:25
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:117:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  19) Profiler Agent should get profiles list:
     Error: done() invoked with non-Error: Error: Unknown command "Profiler.getProfileHeaders" in request
      at /Users/jimthedev/projects/node-inspector/node_modules/mocha/lib/runnable.js:223:25
      at /Users/jimthedev/projects/node-inspector/test/ProfilerAgent.js:72:25
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:117:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)

  20) Profiler Agent should clear profiles:
     Error: done() invoked with non-Error: Error: Unknown command "Profiler.clearProfiles" in request
      at /Users/jimthedev/projects/node-inspector/node_modules/mocha/lib/runnable.js:223:25
      at /Users/jimthedev/projects/node-inspector/test/ProfilerAgent.js:80:25
      at /Users/jimthedev/projects/node-inspector/lib/DebuggerClient.js:117:7
      at Object.create.processResponse.value (/Users/jimthedev/projects/node-inspector/lib/callback.js:23:20)
      at Debugger._processResponse (/Users/jimthedev/projects/node-inspector/lib/debugger.js:92:21)
      at Protocol.execute (_debugger.js:117:14)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:109:10)
      at TCP.onread (net.js:510:20)
```

**Comment by bajtos** [comment] 2015-03-04 09:16
Closing as a duplicate of #546. You can downgrade to `node-inspector@0.7` as a workaround until the full support is implemented.

**Closed by bajtos** 2015-03-04 09:16 UTC

**Comment by jimthedev** [comment] 2015-03-04 23:01
@bajtos I'm assuming you mean duplicate of #523?

**Comment by bajtos** [comment] 2015-03-06 10:00
@jimthedev Of course, thank you for correcting me!
