### ISSUE TITLE
When installing on node 6.9.2 the following errors appear, and node-inspector does not work.

### ISSUE THREAD

**Issue by diegoug** [node-inspector/node-inspector#961] opened 2016-12-19 04:26 UTC
```
RUN npm install -g node-inspector@0.12.8 supervisor@0.11.0 forever@0.15.3
 ---> Running in 32a91b49c688

npm WARN lifecycle v8-debug@0.7.7~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.7.7 node -e 'process.exit(0)' /usr/local/lib/node_modules/.staging/v8-debug-5be573b2
npm WARN lifecycle v8-profiler@5.6.5~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.6.5 node -e 'process.exit(0)' /usr/local/lib/node_modules/.staging/v8-profiler-4971d27a

/usr/local/bin/forever -> /usr/local/lib/node_modules/forever/bin/forever
/usr/local/bin/node-inspector -> /usr/local/lib/node_modules/node-inspector/bin/inspector.js
/usr/local/bin/node-debug -> /usr/local/lib/node_modules/node-inspector/bin/node-debug.js
/usr/local/bin/node-supervisor -> /usr/local/lib/node_modules/supervisor/lib/cli-wrapper.js
/usr/local/bin/supervisor -> /usr/local/lib/node_modules/supervisor/lib/cli-wrapper.js

> v8-debug@0.7.7 install /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v48-linux-x64/debug.node" is installed via remote

> v8-profiler@5.6.5 install /usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "/usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.6.5/node-v48-linux-x64/profiler.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
/usr/local/lib
[......]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/forever/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by replete** [comment] 2016-12-19 17:06
I had this issue on 7.x.
Literally just did this in 6.9.2 fine.

If you're using nvm: `nvm use 6.9.2`

**Comment by replete** [comment] 2016-12-19 17:06
Also, dupe of #914

**Comment by h1orz** [comment] 2017-01-04 17:34
Also not work in 6.9.1/6.9.3, same error.
just work in node 4.x.

**Comment by sunOpar** [comment] 2017-01-25 03:52
the same issue on node v7.3.0

**Comment by johnbahamon** [comment] 2017-01-25 20:00
=(

**Comment by tylik1** [comment] 2017-02-09 16:49
Same thing, works on 4.7.1 and doesn't work on 6+ and 7+
Would be great to see that fixed, as this is the Greatest extension ever, to debug node.js

**Comment by hustxiaoc** [comment] 2017-04-13 04:01
It should work now, please upgrade to `1.1.0`

**Closed by hustxiaoc** 2017-04-13 04:01 UTC
