### ISSUE TITLE
debugged process crashes sporadically: 'Error: Cannot switch to old mode now.'

### ISSUE THREAD

**Issue by david-knipe-hp** [node-inspector/node-inspector#757] opened 2015-09-30 11:50 UTC
When I run a nodejs process with node-inspector, it works fine for a few minutes with heavyish load but then crashes:
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:748:11)
    at IncomingMessage.Readable.resume (_stream_readable.js:733:3)
    at ClientRequest.handleHttpResponse (/home/vagrant/node_modules/node-inspector/lib/Injections/NetworkAgent.js:299:16)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:117:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1692:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1587:20)
    at CleartextStream.read [as _read] (tls.js:513:12)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.write [as _write] (tls.js:368:25)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at EncryptedStream.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)
    at flow (_stream_readable.js:610:7)
    at Socket.pipeOnReadable (_stream_readable.js:642:5)
This happens even when there are no active breakpoints. I'm running node-inspector 0.12.3 . Both node-inspector and the debugged process are running nodejs v0.10.32 . It's in Ubuntu.

**Comment by haciendadad** [comment] 2015-11-09 17:26
I have the same issue, I wish someone has some clues to the cause.

**Comment by 3y3** [comment] 2015-12-06 20:52
Should be fixed in 0.12.5
Feel free to reopen this issue if it still exist.

**Closed by 3y3** 2015-12-06 20:52 UTC
