### ISSUE TITLE
`can not ready property `error occurs within lib\InjectorClient.js

### ISSUE THREAD

**Issue by carlisliu** [node-inspector/node-inspector#953] opened 2016-11-28 07:14 UTC
My environments are as follow:
node-inspector version: 0.12.8
node.js version: 6.9.1
os: windows 10 pro, 64-bit

when start debugging a nodejs app which is generated by thinkjs cli [https://github.com/75team/thinkjs](url) , my console keeps showing the following error
![node-inspector-crush](https://cloud.githubusercontent.com/assets/2157653/20659177/e088c82c-b57c-11e6-9af5-3aab8595aec0.png)

but when i change nodejs version from v6.9.1 to v5.4.1, the error is gone. Maybe node-inspector is conflicted with the latest version of nodejs somehow?

**Comment by borislemke** [comment] 2016-12-15 08:02
First I was using `node@7.2.1`, has errors with `node-gyp`, uninstalled and installed `node@6.9.2`, `node-gyp` errors gone, installed `node-inspector` and getting the above errors. Now installing `node@5.4.1` and above error gone but getting others errors as I'm using ES6 syntax in my `express` app.

UGH 😤

**Comment by kazaff** [comment] 2016-12-26 07:15
me too.

and waiting answer~~~~

**Comment by tharders** [comment] 2017-01-04 08:52
This is a duplicate of #905
https://github.com/node-inspector/node-inspector/issues/905

**Comment by hustxiaoc** [comment] 2017-03-29 01:23
The issue has been resolved, try `node-inspector@1.0.0` please!

**Closed by hustxiaoc** 2017-03-29 01:23 UTC
