### ISSUE TITLE
Complete application crash when console.log()ing an object

### ISSUE THREAD

**Issue by prawnsalad** [node-inspector/node-inspector#823] opened 2016-02-10 13:41 UTC
node v4.2.6
Node Inspector v0.12.6

On tracing it the crash occurs in vm.js.

~~~javascript
exports.runInDebugContext = function(code) {
  return binding.runInDebugContext(code);
};
~~~

Called from util.js:
~~~javascript
function ensureDebugIsInitialized() {
  if (Debug === undefined) {
    const runInDebugContext = require('vm').runInDebugContext;
    Debug = runInDebugContext('Debug');
  }
}
~~~

**Comment by 3y3** [comment] 2016-02-10 14:11
Small example of code where I can debug this?

**Comment by gzzhanghao** [comment] 2016-02-10 14:26
It's a nodejs bug and was fixed in the latest version of node. See https://github.com/nodejs/node/pull/4819 .

Maybe we should provide a hotfix for this since it affects a large range of node version (broken since v4.2.4)

**Comment by 3y3** [comment] 2016-02-10 14:36
Latest 4.2.* releases have some other bugs in debugger. (Does not possible to inspect promises. Sometimes debugger can't respond on `evaluate` request, if it is not paused)
So, debugging on latest 4.2.* and 5.* is painful.
I'm not sure that one hotfix will be useful here.

**Comment by prawnsalad** [comment] 2016-02-10 14:48
I'll try with some different node versions, but for completeness this is how to reproduce it 100% of the time:

~~~javascript
console.log({im: 'an object'});
console.log(1);
setTimeout(function() {}, 100000);
~~~

Interestingly, it only happens when console.log()ing in that order with this snippet with the 2 separate calls. Though I'm sure it must happen in other orders as my application currently has a lot of debugging output but no numbers.

**Comment by prawnsalad** [comment] 2016-02-10 15:08
Quick tests on that snippet:
Node 0.12: works
Node 4: crashes
Node 5: works

**Comment by 3y3** [comment] 2016-02-10 15:16
Are you tested on 4.3?

**Comment by prawnsalad** [comment] 2016-02-10 15:34
@3y3 Yes. 4.2 and 4.3 crashes

**Comment by gzzhanghao** [comment] 2016-02-11 01:59
Also crashes in 5.1, here is a minimum reproduction of it:

```
// test.js
require('vm').runInDebugContext('Debug');
```

Run `node --debug-brk test` and `node debug localhost:5858`, node crashes just after you step over the runInDebugContext method. 

Overriding vm.runInDebugContext may help, it's the only method I found that leads to this issue.

**Comment by derenio** [comment] 2016-02-12 14:54
This might be related to https://github.com/nodejs/node/issues/4261
It started to work for me from `5.4.1`, then with `5.5.0` `node-inspector` stopped breaking on `debugger` and `breakpoints`. Just installed `5.6.0-r1` and so far debugging seems to work.

**Comment by gijohn** [comment] 2016-02-16 13:13
Any update on this issue?

**Comment by 3y3** [comment] 2016-04-08 22:10
This is a node bag. Should be fixed in latest node versions.

**Closed** 2016-04-08 22:11 UTC
Labels: node.js, Third party
