### ISSUE TITLE
Cannot set break within a module loaded with require

### ISSUE THREAD

**Issue by vytronics** [node-inspector/node-inspector#416] opened 2014-08-03 18:50 UTC
Installed 0.7.4 via npm on Windows 8.1 for Chrome 36.0.1985.125. Will not break on a breakpoint set within a module loaded with require via web page client. Will pause and resume though.

Started node-inspector: 
$ node-inspector
Node Inspector v0.7.4
Visit http://127.0.0.1:8080/debug?port=5858 to start debugging.

Started my node application:
node --debug test.js

Opened debugger link in Chrome. Navigated to my module source and created a breakpoint and script would not break on the selected line. Even tried restarting application to break on first line and then add breakpoint in module.

Downgraded to 0.1.10
npm uninstall -g node-inspector
npm install -g node-inspector@0.1.10

Started node application to break on first line
node --debug-brk test.js

Then navigated to module source and added breakpoint. Works!

**Comment by bajtos** [comment] 2015-01-05 09:58
> Any program does

I have very little time to work on Node Inspector these days. By providing the simplest possible program that reproduces your issue, you allow me to immediately start investigating the problem, instead of spending extra time trying to write such program myself.

> It worked in previous node-inspector versions, so it seems not V8-related?

What is the latest node-inspector version that works as expected? What is the first version that does not work?

**Comment by yeonhoyoon** [comment] 2015-04-25 05:40
I had the same problem using node v0.12.2. downgraded to node v0.10.38 and the issue is fixed.

**Comment by durz** [comment] 2015-05-07 00:56
+1

Node inspector in use is v0.10.0 with node v0.12.2.

How to reproduce:

1. Clone https://github.com/durz/node-inspector-416
2. Start the project in debug mode (`node --debug-brk index.js`)
3. Start node-inspector (`node-inspector`)
4. Browse to node-inspector UI in Chrome (http://127.0.0.1:8080/debug?ws=127.0.0.1:8080&port=5858)
5. Set a breakpoint on line 3 of `index.js` (on `var result = thing.doSomething();`)
6. Resume execution.
7. When the breakpoint on line 3 is hit, do a step into.
8. The debugger skips straight to line 4 (`console.log(result);`) instead of going into `thing.js`.

Workaround as suggested above is to downgrade to node v0.10.38.

**Comment by 3y3** [comment] 2015-05-13 21:40
Fixed in 0.10.1

**Closed by 3y3** 2015-05-13 21:40 UTC
Labels: BUG
