### ISSUE TITLE
node-inspector server crashes on page reload (node v4)

### ISSUE THREAD

**Issue by vladikoff** [node-inspector/node-inspector#756] opened 2015-09-26 20:01 UTC
```
Node Inspector v0.12.3
Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.
undefined:1
TypeError: this.extendedProcessDebugJSONRequest_ is not a function
^

SyntaxError: Unexpected token T
    at Object.parse (native)
    at Protocol.execute (_debugger.js:117:43)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
➜  clinic  

```

## STR

Start `node-inspector` in one terminal window
Start a script to debug `node --debug-brk program.js` in another window

Refresh the tab that has the node inspector ui open: http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858

Inspector crashes: 

![image](https://cloud.githubusercontent.com/assets/128755/10119576/cccc0680-6467-11e5-9deb-6c78c316c3c5.png)

**Comment by ElliotChong** [comment] 2015-10-05 01:59
@vladikoff Did you ever find a workaround for this issue? I'm hitting it as well.

**Comment by jcollum** [comment] 2015-10-19 21:46
>  but an uninstall / install did.

Uninstall of Node-inspector?

**Comment by EricFortin** [comment] 2015-11-02 16:01
Restarting the debugged node process(and obviously node-inspector) is enough for me, no need to uninstall anything. Was hitting F5 to continue as I am used to Visual Studio shortcut.

**Comment by haciendadad** [comment] 2015-11-09 17:33
Uninstalling and reinstalling fixed my issues.

**Comment by cainjonm** [comment] 2015-12-15 00:59
Modifying https://github.com/node-inspector/v8-debug/blob/master/v8-debug.js#L96 to check if the function exists before calling it seems to fix this issue... however this doesnt seem to be the correct fix (given that this is caused by the 'close' event being sent, line 140)

@3y3 What would the correct way to fix this issue be? Is there some event that can be hooked to reinitialize after disconnect? (Admittedly I don't have the greatest understanding of how this all fits together).

**Comment by malei0311** [comment] 2015-12-17 08:57
has the same problem

**Comment by Mule52** [comment] 2016-01-02 00:03
Having the same problem right now. I cannot seem to find a reliable way to debug node via vim or terminal.

**Comment by jcollum** [comment] 2016-01-02 00:06
@Mule52 use `ps aux | grep node` and kill the process  that you were trying to debug. That's the only thing that every works for me.

**Comment by Mule52** [comment] 2016-01-02 00:26
@jcollum, thanks for the response. 

Can you help me understand if I am debugging correctly? Via terminal (Linux Mint), I run "node --debug server.js" without the quotes. Then in another terminal window (using tmux), I run "node-inspector &" and open up my chrome dev tools. I then set breakpoints via the node-inspector dev tools. I refresh my client app in another chrome window and try to trigger the breakpoints I just set. I seem to hit these intermittently. I have not found a reliable way to debug this setup as of yet. 

Am I on the right track with my debug setup/init commands?

Thanks.

**Comment by jcollum** [comment] 2016-01-02 00:53
Yes. I like to put one `debugger` command at the top of the file that I'm trying to debug. I've found that the debugger doesn't stop on breakpoints very reliably if it hasn't stopped lately. If that makes any sense; hard to explain.

**Comment by svicalifornia** [comment] 2016-01-23 11:39
How to reproduce this reliably:
1. Get node-inspector to stop at a breakpoint (or debugger statement, or first line with --debug-brk).
2. Reload the node-inspector page.

It seems that node-inspector is not expecting a page reload while at a breakpoint, and it freaks out and dies.

**Comment by svicalifornia** [comment] 2016-01-23 12:07
I've submitted a PR to the v8-debug repo at https://github.com/node-inspector/v8-debug/pull/22

**Comment by svicalifornia** [comment] 2016-01-25 22:55
The above PR has been merged. This issue should be fixed with the next releast of v8-debug.

**Comment by jcollum** [comment] 2016-01-25 22:58
I'd just like to say how great it is that things like this get fixed. I'm used to the Microsoft world: "Yeah, that's broken, it'll get fixed in the next major release. Probably. Or that feature will be changed."

**Comment by 3y3** [comment] 2016-01-25 23:00
I need some time to release new v8-debug version (build prebuld binaries in cloud).

**Comment by 3y3** [comment] 2016-01-25 23:41
new v8-debug released

**Closed by 3y3** 2016-01-25 23:41 UTC

**Comment by svicalifornia** [comment] 2016-01-26 04:19
Wow, thanks!

**Comment by jcollum** [comment] 2016-02-04 21:25
I've been doing a lot of debugging the last few days and this bugfix has helped a lot. The tool is much more stable on my Mac now -- I never have to go and kill the NI process and my node processes and start from scratch. Thanks for solving this  issue  @svicalifornia

**Comment by svicalifornia** [comment] 2016-02-05 00:50
@jcollum You're welcome!

**Comment by ElliotChong** [comment] 2016-02-05 01:04
:clap: :+1: Many thanks @svicalifornia! :)
