### ISSUE TITLE
Can't set breakpoint via web inspector UI (iojs with babel)

### ISSUE THREAD

**Issue by th0r** [node-inspector/node-inspector#628] opened 2015-04-30 22:25 UTC
I've recorded short video, displaying this bug: http://youtu.be/odIFQ1DNCAc
I'm using `iojs v1.8.1` with `babel 5.1.13`, which transpiles scripts via `require` hook and generates inline sourcemaps.
If you need some additional info, just ask.

**Comment by cr0cK** [comment] 2015-05-11 13:55
I have exactly the same problem and it's annoying.

I start the serveur with :
./node_modules/.bin/babel-node --debug --stage 1 index.js

**Comment by rollokb** [comment] 2015-05-14 10:53
I also have this problem. I need a fix urgently

**Comment by 3y3** [comment] 2015-05-14 11:47
Looks like a duplication of https://github.com/node-inspector/node-inspector/issues/580

**Comment by 3y3** [comment] 2015-05-14 11:48
Provide me please very small example to reproduce this problem.

**Comment by cr0cK** [comment] 2015-05-14 21:49
I push a small example where I can reproduce the bug: https://github.com/cr0cK/node-inspector-issue628

Tested version are in the README of the example.

**Comment by marcominetti** [comment] 2015-05-15 09:09
Thanks @cr0cK... I'll investigate during the we...

**Comment by marcominetti** [comment] 2015-05-15 09:31
Ok, problem found... It's related with file naming... Seems node-inspector is not able to handle the case when the compiled and loaded script uri (e.g. /home/marco.minetti/Desktop/node-inspector-issue628/app/classes.js) is identical to the source file uri embedded in the sourcemap...

I'll try to fix it during the weekend... just as workaround, in my projects I force babel and acorn to use fake (virtual) source paths to keep compiled and source uri different... but with inline sourcemap this is not the case...

**Comment by marcominetti** [comment] 2015-05-15 09:33
@3y3 Yuri, when you have time can you send me the repo where the blink tools source code is available... maybe they have fixed something after new frontend merge...

**Comment by 3y3** [comment] 2015-05-15 09:52
@marcominetti , I already have in plans to test front-end update (with new front-end system, this promises to be simple), so, if you want it soon, I'll make it on this evening or on weekend.

**Comment by marcominetti** [comment] 2015-05-15 10:06
@3y3 could be useful, but I've created a workaround with duplication of entries in resource tree, I mean you get two files (file://classes.js - the original - and built://classes.js - the transpiled that could be also hidden)... let me know if it sounds reasonable for you in here or wants to delve into it...

**Comment by 3y3** [comment] 2015-05-15 10:25
@marcominetti , can you open a pr to look on progress?

**Comment by marcominetti** [comment] 2015-05-15 12:17
yep, i'll do asap during the weekend... ;)

**Comment by 3y3** [comment] 2015-06-14 21:47
Fixed in 0.10.2.
Feel free to reopen this issue, if I'm wrong here.

**Closed by 3y3** 2015-06-14 21:48 UTC
Labels: BUG
